In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import math

In [3]:
data = pd.read_csv("C:/Users/hp/Desktop/Everything/Work/Projects/classification problems/heart.csv")
df = pd.DataFrame(data)

In [6]:
df.head(5)

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [12]:
#change column values to desired output 0s and 1s 
df['ExerciseAngina'] = df['ExerciseAngina'].replace({ 'Y': 1 , 'N' : 0})
df['ExerciseAngina'] = pd.to_numeric(df['ExerciseAngina'])

In [17]:
df['ones'] = 1

In [26]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,ones
0,40,M,ATA,140,289,0,Normal,172,0,0.0,Up,0,1
1,49,F,NAP,160,180,0,Normal,156,0,1.0,Flat,1,1
2,37,M,ATA,130,283,0,ST,98,0,0.0,Up,0,1
3,48,F,ASY,138,214,0,Normal,108,1,1.5,Flat,1,1
4,54,M,NAP,150,195,0,Normal,122,0,0.0,Up,0,1

In [92]:

X = df[['ones','RestingBP','Cholesterol','Age']].to_numpy()
y = df[['HeartDisease']].to_numpy()
X[:,1] = (X[:,1] - X[:,1].mean()) / X[:,1].std()
X[:,2] = (X[:,2] - X[:,2].mean()) / X[:,2].std()
X[:,3] = (X[:,3] - X[:,3].mean()) / X[:,3].std()

teta = np.array([[0],[0],[0],[0]])
e = math.e
m = len(X)
alpha = 0.01 
epoch = 100


for i in range(epoch):
    z = X @ teta
    ypred = 1/(1+(np.exp(-z)))
    ypred = np.clip(ypred, 1e-15, 1 - 1e-15)
    error = ypred - y
    grad = (1/m)* (X.T @ error)
    
    teta = teta - (alpha * grad)
print(f"the value of teta predicted are: {teta}")
print(f"the amount of iteration : {i}")


# prediction 
input_RestingBP = 160
Age = 37
Cholesterol = 283

X1 = np.array([[1,input_RestingBP,Cholesterol,Age]]) 
X1[:,1] = (X1[:,1] - X[:,1].mean()) / X[:,1].std()
X1[:,2] = (X1[:,2] - X[:,2].mean()) / X[:,2].std()
X1[:,3] = (X1[:,3] - X[:,3].mean()) / X[:,3].std()

znew = X1 @ teta
ynew = 1/(1+(np.exp(-znew)))


if ynew >= 0.5:
    ynewpred = 1
else:
    ynewpred = 0

#print(ynew.dtype)

print(f" the predicted value of a person with {input_RestingBP} RestingBP : {ynew.item():.7f} {ypred}")

'\nX = df[[\'ones\',\'RestingBP\',\'Cholesterol\',\'Age\']].to_numpy()\ny = df[[\'HeartDisease\']].to_numpy()\nX[:,1] = (X[:,1] - X[:,1].mean()) / X[:,1].std()\nX[:,2] = (X[:,2] - X[:,2].mean()) / X[:,2].std()\nX[:,3] = (X[:,3] - X[:,3].mean()) / X[:,3].std()\n\nteta = np.array([[0],[0],[0],[0]])\ne = math.e\nm = len(X)\nalpha = 0.01 \nepoch = 100\n\n\nfor i in range(epoch):\n    z = X @ teta\n    ypred = 1/(1+(np.exp(-z)))\n    ypred = np.clip(ypred, 1e-15, 1 - 1e-15)\n    error = ypred - y\n    grad = (1/m)* (X.T @ error)\n    \n    teta = teta - (alpha * grad)\nprint(f"the value of teta predicted are: {teta}")\nprint(f"the amount of iteration : {i}")\n\n\n# prediction \ninput_RestingBP = 160\nAge = 37\nCholesterol = 283\n\nX1 = np.array([[1,input_RestingBP,Cholesterol,Age]]) \nX1[:,1] = (X1[:,1] - X[:,1].mean()) / X[:,1].std()\nX1[:,2] = (X1[:,2] - X[:,2].mean()) / X[:,2].std()\nX1[:,3] = (X1[:,3] - X[:,3].mean()) / X[:,3].std()\n\nznew = X1 @ teta\nynew = 1/(1+(np.exp(-znew)))\n\n\nif ynew >= 0.5:\n    ynewpred = 1\nelse:\n    ynewpred = 0\n\n#print(ynew.dtype)\n\nprint(f" the predicted value of a person with {input_RestingBP} RestingBP : {ynew.item():.7f} {ypred}")\n'

In [102]:
import numpy as np

class LogisticRegressionScratch:
    def __init__(self, learning_rate=0.01, iterations=1000):
        self.lr = learning_rate
        self.iterations = iterations
        self.theta = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        m, n = X.shape

        # Add bias term
        X = np.c_[np.ones((m, 1)), X]

        # Initialize parameters
        self.theta = np.zeros(n + 1)

        for _ in range(self.iterations):
            z = np.dot(X, self.theta)
            h = self.sigmoid(z)

            # Gradient
            gradient = (1 / m) * np.dot(X.T, (h - y))

            # Update
            self.theta -= self.lr * gradient

    def predict_proba(self, X):
        m = X.shape[0]
        X = np.c_[np.ones((m, 1)), X]
        return self.sigmoid(np.dot(X, self.theta))

    def predict(self, X, threshold=0.5):
        probs = self.predict_proba(X)
        return (probs >= threshold).astype(int)

X1 = df[['RestingBP','Cholesterol','Age']].to_numpy()
y1 = df[['HeartDisease']].to_numpy().flatten()
X1[:,0] = (X1[:,0] - X1[:,0].mean()) / X1[:,0].std()
X1[:,1] = (X1[:,1] - X1[:,1].mean()) / X1[:,1].std()
X1[:,2] = (X1[:,2] - X1[:,2].mean()) / X1[:,2].std()

model = LogisticRegressionScratch(learning_rate=0.1, iterations=1000)
model.fit(X1, y1)

predictions = model.predict()
print(predictions)

# Generate smooth curve
X1_plot = np.linspace(0, 6, 100).reshape(-1, 1)
y1_prob = model.predict_proba(X_plot)

# Plot
plt.figure()
plt.scatter(X, y)
plt.plot(X_plot, y_prob)
plt.xlabel("X")
plt.ylabel("Probability")
plt.title("Logistic Regression Fit")
plt.show()

[0 1 0 1 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1
 0 1 1 1 1 0 1 0 0 0 1 0 0 1 1 1 0 1 1 0 1 0 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0
 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 1
 1 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0
 1 0 0 1 0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 0 1 1 0 1 1 1 0 1 0
 1 1 0 0 1 1 1 1 1 0 1 1 0 1 1 1 1 0 0 1 1 0 0 0 1 1 1 1 1 1 0 0 1 1 0 1 1
 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1
 0 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1
 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1 0
 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 0 0 1 1 0 1 0 1 0 1 1
 0 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 0 1
 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 0 1 0 1 1 1 0 1 1 1 1
 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0
 1 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0]

ValueError: shapes (100,2) and (4,) not aligned: 2 (dim 1) != 4 (dim 0)

In [103]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,ones
0,40,M,ATA,140,289,0,Normal,172,0,0.0,Up,0,1
1,49,F,NAP,160,180,0,Normal,156,0,1.0,Flat,1,1
2,37,M,ATA,130,283,0,ST,98,0,0.0,Up,0,1
3,48,F,ASY,138,214,0,Normal,108,1,1.5,Flat,1,1
4,54,M,NAP,150,195,0,Normal,122,0,0.0,Up,0,1